language: java

branches:
  only:
    - master
before_deploy: export TRAVIS_TAG=$(date +'%Y.%m.%d.%H:%M.%S')
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: ./target/bspsrc*
  name: $(date +'%Y.%m.%d.%H:%M.%S')
