language: java

after_script:
- ls ./target

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./target/bspsrc*
  name: $(date +'%Y.%m.%d.%H:%M.%S')
